# NAME: Derek Xu
# EMAIL: derekqxu@g.ucla.edu
# ID: 704751588

CC = gcc
CFLAGS = -g -Wall -Wextra

default:
	$(CC) $(CFLAGS) lab1a.c -o lab1a

clean:
	rm -f lab1a *.tar.gz

dist:
	tar -czvf lab1a-704751588.tar.gz lab1a.c Makefile README
