# NAME: Derek Xu,Harry Yee
# EMAIL: derekqxu@g.ucla.edu,hyee1234@gmail.com
# ID: 704751588,704754172

CC = gcc
CFLAGS = -Wall -Wextra

build:
	$(CC) $(CFLAGS) -o lab3a lab3a.c

clean:
	rm -f lab3a *.tar.gz

dist:
	tar -czvf lab3a-704751588.tar.gz lab3a.c Makefile README ext2_fs.h

