# NAME: Derek Xu,Harry Yee
# EMAIL: derekqxu@g.ucla.edu,hyee1234@gmail.com
# ID: 704751588,704754172

.SILENT:
build:
	chmod +x lab3b.py
	-ln lab3b.py lab3b
	echo "Successful built"

clean:
	rm -f lab3b *.tar.gz

dist:
	tar -czvf lab3b-704751588.tar.gz lab3b.py Makefile README

